### ISSUE TITLE
Compiled on H3, not working.

### ISSUE THREAD

**Issue by ivanholmes** [stulluk/FFmpeg-Cedrus#6]
When I try to use your ffmpeg to transcode a file to H.264 this is the output I get:

ffmpeg -i bbb.divx -c:v cedrus264 -c:a copy -pix_fmt nv12 out.mkv
ffmpeg version git-2015-01-22-f86a076 Copyright (c) 2000-2014 the FFmpeg developers
  built on Jun 12 2016 22:15:02 with gcc 4.9.2 (Debian 4.9.2-10)
  configuration: 
  libavutil      54.  6.100 / 54.  6.100
  libavcodec     56.  0.101 / 56.  0.101
  libavformat    56.  2.100 / 56.  2.100
  libavdevice    56.  0.100 / 56.  0.100
  libavfilter     5.  0.102 /  5.  0.102
  libswscale      3.  0.100 /  3.  0.100
  libswresample   1.  1.100 /  1.  1.100
Input #0, avi, from 'bbb.divx':
  Duration: 00:10:17.33, start: 0.000000, bitrate: 3584 kb/s
    Stream #0:0: Video: mpeg4 (DX50 / 0x30355844), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 2997 kb/s, 24 fps, 24 tbr, 24 tbn, 30k tbc
    Metadata:
      title           : Video 
    Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 48000 Hz, stereo, s16p, 192 kb/s
    Metadata:
      title           : Audio 
    Stream #0:2: Audio: ac3 ([0] [0][0] / 0x2000), 48000 Hz, 5.1(side), fltp, 384 kb/s
    Metadata:
      title           : Audio 
File 'out.mkv' already exists. Overwrite ? [y/N] y
[VE SUNXI] VE version 0x0000 opened.
[cedrus264 @ 0x1c50cf0] Cannot allocate frame.
Output #0, matroska, to 'out.mkv':
    Stream #0:0: Video: h264, q=2-31, 128 kb/s, SAR 1:1 DAR 0:0, 24 fps
    Metadata:
      title           : Video 
      encoder         : Lavc56.0.101 cedrus264
    Stream #0:1: Audio: none, 0 channels, 128 kb/s
    Metadata:
      title           : Audio 
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg4 (native) -> h264 (cedrus264))
  Stream #0:2 -> #0:1 (copy)
Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height

I tried to use the .deb file version but that did not work either so I had to compile from source.
Thanks
Ivan

**Comment by ShienXie** [comment]
Got same problem, has this issue been solved? I am using pine A64 with Armbian.

root@pine64:~# ffmpeg -i jellyfish-5-mbps-hd-h264.mkv -pix_fmt nv12 -c:v cedrus264 -f null /dev/null
ffmpeg version git-2015-01-22-f86a076 Copyright (c) 2000-2014 the FFmpeg developers
  built on Jul  7 2017 21:53:21 with gcc 5.4.0 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr --enable-nonfree --enable-gpl --enable-version3 --enable-vdpau --enable-libx264 --enable-libmp3lame --enable-libpulse --enable-libv4l2
  libavutil      54.  6.100 / 54.  6.100
  libavcodec     56.  0.101 / 56.  0.101
  libavformat    56.  2.100 / 56.  2.100
  libavdevice    56.  0.100 / 56.  0.100
  libavfilter     5.  0.102 /  5.  0.102
  libswscale      3.  0.100 /  3.  0.100
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  0.100 / 53.  0.100
Input #0, matroska,webm, from 'jellyfish-5-mbps-hd-h264.mkv':
  Metadata:
    encoder         : libebml v1.2.0 + libmatroska v1.1.0
    creation_time   : 2016-02-06 04:00:51
  Duration: 00:00:30.03, start: 0.000000, bitrate: 4976 kb/s
    Stream #0:0(eng): Video: h264 (High), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 29.97 fps, 29.97 tbr, 1k tbn, 59.94 tbc (default)
[VDPAU SUNXI] VE version 0x1689 opened.
ION_IOC_ALLOC failed: No such device
ION_IOC_ALLOC failed: No such device
ION_IOC_ALLOC failed: No such device
ION_IOC_ALLOC failed: No such device
ION_IOC_ALLOC failed: No such device
[cedrus264 @ 0x14d1710] Cannot allocate frame.
Output #0, null, to '/dev/null':
  Metadata:
    encoder         : libebml v1.2.0 + libmatroska v1.1.0
    Stream #0:0(eng): Video: h264, q=2-31, 128 kb/s, SAR 1:1 DAR 0:0, 29.97 fps (default)
    Metadata:
      encoder         : Lavc56.0.101 cedrus264
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (cedrus264))
Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height

**Comment by jasimar** [comment]
HI,
Did you  solve the issue

**Comment by stulluk** [comment]
Hi,
I am aware of all issues, and I always get the notifications for such issues, but sadly I don't have time & resource to look back to this repository which I created 12 years ago.

Therefore I apologise to everyone that nobody is getting a useful result with this repo.

Please remember that, back then 12 years ago, there was vendor kernel ( 3.14 I guess ) and if I remember correctly, the changes we made to original ffmpeg source was targeted at that kernel and userland.

I have not touched to this repo anymore, since there should be way more better solutions than this repo out there in https://linux-sunxi.org/Cedrus

Can anybody tell me, why this repo is still getting some attention ? Does above mainline solutions don't work ?

**Comment by ivanholmes** [comment]
I agree that this issue is not relevant any more. I will close it to encourage people to use the mainline solution!

**Comment by stulluk** [comment]
Thank you @ivanholmes for your understanding & considerations. 
I hope one day somebody writes a clear tutorial regarding how to encode & decode multimedia with mainline kernel & mainline userland with Sunxi SoC's.
Regards.
